name: calendar_scheduler
description: "일정 관리 앱"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  table_calendar: ^3.1.0
  intl: ^0.19.0
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  get_it: ^7.6.7
  dio: ^5.4.1
  provider: ^6.1.2
  uuid: ^4.3.3
  fluttertoast: ^8.2.4
  firebase_core: ^2.27.2
  cloud_firestore: ^4.15.10


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  drift_dev: ^2.16.0

  build_runner: ^2.4.8


flutter:


  uses-material-design: true

  assets:
    - assets/images/
